name: Detail server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.0.0'
      - run: |
          touch .env
          echo PORT=$PORT >> .env
          echo DB_URL=$DB_URL >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          echo STRIPE_SECRET_TEST=$STRIPE_SECRET_TEST >> .env
          npm i
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
        env:
          PORT: ${{ secrets.PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_SECRET_TEST: ${{ secrets.STRIPE_SECRET_TEST }}


